### ISSUE TITLE
PortPy with Monaco

### ISSUE THREAD

**Issue by zism** [PortPy-Project/PortPy#7]
Hi, I would like to know how to link PortPy with Monaco TPS (5.11).

**Comment by masoudzp** [comment]
The DICOM-RT generated by PortPy for IMRT or VMAT can be imported to Monaco, but some dose discrepancies are expected since Eclipse-AAA has been used for dose calculation for the lung dataset. At this point, you cannot import IMRT optimal fluence into Monaco and you also cannot use Monaco dose calculation for optimization.

**Comment by zism** [comment]
will be any advances in the future?

**Comment by masoudzp** [comment]
We're actively developing PortPy and our ultimate goal is to integrate it with all widely used TPSs. However, I don't know when we would be able to integrate with Monaco. We welcome anyone who's willing to contribute
